services:
  - type: web
    name: trhacknon-dork-scanner
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000 --workers 2"
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # configure cette clé dans l'interface Render
      - key: SERPAPI_KEY
        sync: false  # configure aussi cette clé dans Render
    autoDeploy: true
