services:
  - type: web
    name: trhacknon-dork-scanner
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: OPENAI_API_KEY
        value: sk-xxxxxx # ou configure-la dans l'interface Render
    autoDeploy: true
